# Exclude specific files and directories from the build
exclude:
  - build_and_serve.sh
  - .DS_Store
  - .gitignore
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - README.md
  - .vscode
  - .ruby-version
  - /fonts/geomanist/demo.html
  
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  
# For local development, we build css with the "expanded" format to produce
# human-readable output for easier debugging.
sass:
  sass_dir: _scss
  style: expanded
  
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: docs
      toc_min: 2
      toc_max: 3

      
collections:
  samples:
    output: true

